# Site language
lang: ja

# Site title
title: "CodeGenesis-2024"

# A description of your site for meta tag, search engine results.
description: "開発経歴や自分がどんな業務をやってきたかを残す"

# domain: /kazukikanomata.github.io
url: "https://kazukikanomata.github.io"
baseurl: ""


# Favicon
favicon: /assets/images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Work
    url: /work
  - text: Showcase
    url: /showcase

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; Scriptor all rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
